import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir,stat} from 'node:fs/promises';import {pool,answerDigest,correctLabel,checkAnswer,chooseQuestion,Progress,sanitizeProgress} from '../src/core.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}};
test('retirement persists; incorrect answers remain; reset and imports work',()=>{const s=memory(),allowed=new Set(['a','b']);const p=new Progress(s,'test',allowed);p.record('a',false);assert.equal(p.state.mastered.a,undefined);p.record('a',true);assert.ok(new Progress(s,'test',allowed).state.mastered.a);assert.equal(chooseQuestion([{id:'a'},{id:'b'}],p.state.mastered).id,'b');p.import({version:1,mastered:{b:new Date().toISOString(),foreign:new Date().toISOString()},attempts:{b:2}});assert.equal(chooseQuestion([{id:'a'},{id:'b'}],p.state.mastered),null);assert.equal(p.state.mastered.foreign,undefined);p.reset();assert.equal(Object.keys(new Progress(s,'test',allowed).state.mastered).length,0);assert.throws(()=>p.record('foreign',true));});
test('random selection avoids repeats and handles completion',()=>{const rows=[{id:'a'},{id:'b'},{id:'c'}];assert.equal(chooseQuestion(rows,{},'a',()=>0).id,'b');assert.equal(chooseQuestion(rows,{},null,()=>1).id,'c');assert.equal(chooseQuestion([],{}),null);});
test('unavailable and corrupt storage never claim persistence',()=>{const p=new Progress({getItem(){throw Error()},setItem(){throw Error()}},'x',new Set(['a']));p.record('a',true);assert.equal(p.persistent,false);assert.ok(p.state.mastered.a);assert.throws(()=>sanitizeProgress({version:2,mastered:{}},new Set()));});
test('all packaged answer checks, references and public file boundary',async()=>{const catalog=JSON.parse(await readFile('site/data/catalog.json'));assert.equal(catalog.questions.length,8532);const ids=new Set(catalog.questions.map(q=>q.id));assert.equal(ids.size,8532);assert.ok(!ids.has('he-2016-12-english-1-q08'));assert.ok(!ids.has('he-2024-04-quantitative-1-q17'));let count=0;for(const f of await readdir('site/data/exams')){const batch=JSON.parse(await readFile('site/data/exams/'+f));for(const q of Object.values(batch.questions)){const label=await correctLabel(q);for(let n=1;n<=4;n++)assert.equal(await checkAnswer(q,n),n===label);assert.ok(!('correct_choice_id' in q));assert.ok(!('raw_text' in q));for(const r of q.regions)assert.ok((await stat('site/'+r.asset)).size>0);for(const id of q.contexts)assert.ok(batch.contexts[id]);count++;}for(const c of Object.values(batch.contexts))for(const r of c.images||c.regions)assert.ok((await stat('site/'+r.asset)).size>0);}assert.equal(count,8532);await assert.rejects(stat('site/private-answer-keys.json'));});

test("three subject pools remain separate",()=>{const catalog={questions:[{subject:"quantitative"},{subject:"verbal"},{subject:"english"}]};for(const mode of ["math","verbal","english"])assert.equal(pool(catalog,mode).length,1);assert.equal(pool(catalog,"invalid").length,0);});

test('all question and passage viewport records remain inside original images',async()=>{const crops=JSON.parse(await readFile('site/data/image-crops.json'));let n=0;for(const f of await readdir('site/data/exams')){const batch=JSON.parse(await readFile('site/data/exams/'+f));for(const q of Object.values(batch.questions))for(const r of q.regions){assert.ok(crops[r.asset],r.asset);n++;}for(const c of Object.values(batch.contexts))for(const r of c.images||[])assert.ok(crops[r.asset],r.asset);}for(const m of Object.values(crops)){const [w,h]=m.size,[l,t,r,b]=m.box;assert.ok([w,h,l,t,r,b].every(Number.isFinite));assert.ok(l>=0&&t===0&&r<=w&&b===h&&r>l);assert.ok(r-l>=w*.59);}assert.ok(n>=8532);});
