import {pool,chooseQuestion,Progress,checkAnswer,correctLabel} from './core.js';
const $=id=>document.getElementById(id), base=new URL('./',import.meta.url);
let catalog,progress,current,mode='math',generation=0,graded=false,imageCrops={};
const batches=new Map(),names={math:'חשיבה כמותית',verbal:'חשיבה מילולית',english:'אנגלית'};
let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('Unavailable')},setItem(){throw Error('Unavailable')}};}
const key='psycho-training:v1:'+base.pathname;
async function fetchJSON(path){const r=await fetch(new URL(path,base));if(!r.ok)throw Error('Download failed');return r.json();}
function rows(){return pool(catalog,mode);}
function update(){const list=rows(),done=list.filter(q=>Object.hasOwn(progress.state.mastered,q.id)).length;$('progressText').textContent=`${done.toLocaleString('he')} מתוך ${list.length.toLocaleString('he')} הושלמו`;$('progressBar').max=list.length||1;$('progressBar').value=done;$('storageWarning').hidden=progress.persistent;$('totalProgress').textContent=`${Object.keys(progress.state.mastered).length.toLocaleString('he')} מתוך ${catalog.questions.length.toLocaleString('he')} שאלות הושלמו`;}
function picture(asset,alt){
 const fragment=document.createDocumentFragment(),button=document.createElement('button');button.className='picture-button';button.type='button';button.setAttribute('aria-label','פתיחת התמונה המקורית בהגדלה');
 const scroll=document.createElement('span');scroll.className='picture-scroll';const frame=document.createElement('span');frame.className='picture-viewport';const img=document.createElement('img');img.className='question-image';img.src=new URL(asset,base);img.alt=alt;
 function configure(){const meta=imageCrops[asset]||{size:[img.naturalWidth,img.naturalHeight],box:[0,0,img.naturalWidth,img.naturalHeight]};const [w,h]=meta.size,[left,top,right,bottom]=meta.box;if(!w||!h)return;frame.style.aspectRatio=`${right-left} / ${bottom-top}`;img.style.position='absolute';img.style.width=`${w/(right-left)*100}%`;img.style.left=`${-left/(right-left)*100}%`;img.style.top=`${-top/(bottom-top)*100}%`;frame.dataset.cropped=String(left>0||top>0||right<w||bottom<h);}
 img.addEventListener('load',configure);img.addEventListener('error',()=>{img.alt='התמונה לא נטענה. נסו לבחור שאלה שוב.'});if(imageCrops[asset])configure();frame.append(img);scroll.append(frame);button.append(scroll);
 button.onclick=()=>{$('zoomImage').src=img.src;$('zoomRange').value=100;$('zoomImage').style.width='100%';$('zoomDialog').showModal()};
 const controls=document.createElement('div');controls.className='image-controls';controls.setAttribute('aria-label','גודל התמונה');const output=document.createElement('output');output.setAttribute('aria-live','polite');output.dir='ltr';let scale=100;
 const minus=document.createElement('button'),plus=document.createElement('button'),fit=document.createElement('button');for(const b of [minus,plus,fit]){b.type='button';b.className='image-zoom-button';}minus.textContent='−';minus.dataset.zoom='out';minus.setAttribute('aria-label','הקטנת התמונה בתוך העמוד');plus.textContent='+';plus.dataset.zoom='in';plus.setAttribute('aria-label','הגדלת התמונה בתוך העמוד');fit.textContent='התאמה לרוחב';fit.dataset.zoom='fit';
 function resize(value){scale=value;frame.style.width=scale+'%';output.textContent=scale+'%';minus.disabled=scale===100;plus.disabled=scale===300;requestAnimationFrame(()=>{scroll.scrollLeft=mode==='english'?0:scroll.scrollWidth-scroll.clientWidth;});}
 minus.onclick=()=>resize(Math.max(100,scale-25));plus.onclick=()=>resize(Math.min(300,scale+25));fit.onclick=()=>resize(100);resize(100);controls.append(plus,output,minus,fit);fragment.append(controls,button);return fragment;
}
function context(c){const d=document.createElement('details');d.className='context';const s=document.createElement('summary');s.textContent=c.kind==='complete_section_fallback'?'הפרק המלא':c.kind==='section_instructions'?'הוראות הפרק':c.kind==='reading_passage'?'קטע הקריאה':'הוראות ומידע לשאלה';d.append(s);const regions=c.images||c.regions;d.open=c.kind==='reading_passage'||c.kind==='quantitative_comparison_instructions'||c.kind==='shared_response_instructions'||c.kind==='shared_instructions_or_chart';for(const r of regions)d.append(picture(r.asset,'מידע מקורי לשאלה'));return d;}
async function next(){if(!catalog)return;const token=++generation;progress.load();update();const selected=chooseQuestion(rows(),progress.state.mastered,current?.id,()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296);current=null;graded=false;$('answers').disabled=true;$('checkButton').disabled=true;$('nextButton').disabled=true;$('feedback').hidden=true;document.querySelectorAll('[name=answer]').forEach(r=>{r.checked=false;r.parentElement.classList.remove('correct','incorrect')});$('questionCard').hidden=!selected;$('emptyState').hidden=!!selected;if(!selected)return;$('questionCard').setAttribute('aria-busy','true');$('questionBody').textContent='טוענים שאלה…';try{if(!batches.has(selected.exam))batches.set(selected.exam,fetchJSON(`data/exams/${selected.exam}.json`).catch(e=>{batches.delete(selected.exam);throw e}));const batch=await batches.get(selected.exam);if(token!==generation)return;current=batch.questions[selected.id];$('subjectLabel').textContent=names[mode];$('questionTitle').textContent=`שאלה ${current.number}`;$('sourceTag').textContent=selected.exam.replace('he-','');$('questionBody').replaceChildren();const cs=current.contexts.map(id=>batch.contexts[id]).filter(Boolean);for(const c of cs.filter(c=>c.kind!=='complete_section_fallback'&&c.kind!=='section_instructions'))$('questionBody').append(context(c));for(const r of current.regions)$('questionBody').append(picture(r.asset,'השאלה והתשובות המקוריות'));const hint=document.createElement('p');hint.className='image-hint';hint.textContent='להגדלה השתמשו ב־+ וגררו לצדדים; לתמונה המקורית לחצו על התמונה';$('questionBody').append(hint);for(const c of cs.filter(c=>c.kind==='complete_section_fallback'||c.kind==='section_instructions'))$('questionBody').append(context(c));$('answers').disabled=false;$('nextButton').disabled=false;$('nextButton').textContent='שאלה אחרת';}catch{if(token!==generation)return;$('questionBody').textContent='לא הצלחנו לטעון את השאלה. נסו שוב.';$('nextButton').disabled=false;$('nextButton').textContent='ניסיון נוסף';}finally{if(token===generation)$('questionCard').setAttribute('aria-busy','false');}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));next()});
document.querySelectorAll('[name=answer]').forEach(r=>r.onchange=()=>{$('checkButton').disabled=!current||graded});
$('nextButton').onclick=next;
$('checkButton').onclick=async()=>{const q=current,token=generation,label=Number(document.querySelector('[name=answer]:checked')?.value);if(!q||graded||!label)return;graded=true;$('answers').disabled=true;$('checkButton').disabled=true;try{const ok=await checkAnswer(q,label),answer=ok?label:await correctLabel(q);if(token!==generation)return;progress.record(q.id,ok);update();$('feedback').className=ok?'feedback correct':'feedback incorrect';$('feedback').textContent=ok?'נכון! השאלה הושלמה ולא תופיע שוב.':`התשובה הנכונה היא ${answer}. השאלה נשארת לתרגול.`;$('feedback').hidden=false;document.querySelector(`[name=answer][value="${answer}"]`).parentElement.classList.add('correct');if(!ok)document.querySelector(`[name=answer][value="${label}"]`).parentElement.classList.add('incorrect');$('nextButton').textContent='שאלה הבאה';}catch{graded=false;$('answers').disabled=false;$('checkButton').disabled=false;$('feedback').hidden=false;$('feedback').textContent='הבדיקה נכשלה. נסו שוב.';}};
$('closeZoom').onclick=()=>$('zoomDialog').close();$('zoomRange').oninput=()=>{$('zoomImage').style.width=$('zoomRange').value+'%'};
$('settingsButton').onclick=()=>{if(!progress)return;$('totalProgress').textContent=`${Object.keys(progress.state.mastered).length.toLocaleString('he')} מתוך ${catalog.questions.length.toLocaleString('he')} שאלות הושלמו`;$('settingsDialog').showModal()};$('closeSettings').onclick=()=>$('settingsDialog').close();
$('exportButton').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(progress.state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='psychometric-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)};
$('importInput').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>5000000)throw Error('Too large');progress.import(JSON.parse(await f.text()));$('importFeedback').textContent='הגיבוי יובא בהצלחה.';await next();}catch{$('importFeedback').textContent='לא ניתן לקרוא את הגיבוי. בחרו קובץ התקדמות תקין.';}e.target.value=''};
$('resetButton').onclick=()=>{$('resetConfirm').hidden=false};$('cancelReset').onclick=()=>{$('resetConfirm').hidden=true};$('confirmReset').onclick=()=>{progress.reset();$('resetConfirm').hidden=true;$('settingsDialog').close();next()};
window.addEventListener('storage',e=>{if(e.key===key){progress.load();if(current&&Object.hasOwn(progress.state.mastered,current.id))next();else update()}});
async function init(){try{[catalog,imageCrops]=await Promise.all([fetchJSON('data/catalog.json'),fetchJSON('data/image-crops.json').catch(()=>({}))]);progress=new Progress(storage,key,new Set(catalog.questions.map(q=>q.id)));await next()}catch{$('questionBody').textContent='טעינת המאגר נכשלה. בדקו את החיבור ורעננו את הדף.'}}init();
