import {pool,chooseQuestion,Progress,checkAnswer,correctLabel} from './core.js';
const $=id=>document.getElementById(id), base=new URL('./',import.meta.url);
let catalog,progress,current,mode='math',generation=0,graded=false;
const batches=new Map(),names={math:'חשיבה כמותית',verbal:'חשיבה מילולית',english:'אנגלית'};
let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('Unavailable')},setItem(){throw Error('Unavailable')}};}
const key='psycho-training:v1:'+base.pathname;
async function fetchJSON(path){const r=await fetch(new URL(path,base));if(!r.ok)throw Error('Download failed');return r.json();}
function rows(){return catalog.questions.filter(q=>q.subject===(mode==='math'?'quantitative':mode));}
function update(){const list=rows(),done=list.filter(q=>Object.hasOwn(progress.state.mastered,q.id)).length;$('progressText').textContent=`${done.toLocaleString('he')} מתוך ${list.length.toLocaleString('he')} הושלמו`;$('progressBar').max=list.length||1;$('progressBar').value=done;$('storageWarning').hidden=progress.persistent;}
function picture(asset,alt){const b=document.createElement('button');b.className='picture-button';b.type='button';b.setAttribute('aria-label','הגדלת התמונה');const img=document.createElement('img');img.className='question-image';img.src=new URL(asset,base);img.alt=alt;img.addEventListener('error',()=>{img.alt='התמונה לא נטענה. נסו לבחור שאלה שוב.'});b.append(img);b.onclick=()=>{$('zoomImage').src=img.src;$('zoomRange').value=100;$('zoomImage').style.width='100%';$('zoomDialog').showModal()};return b;}
function context(c){const d=document.createElement('details');d.className='context';const s=document.createElement('summary');s.textContent=c.kind==='complete_section_fallback'?'הפרק המלא':c.kind==='section_instructions'?'הוראות הפרק':c.kind==='reading_passage'?'קטע הקריאה':'הוראות ומידע לשאלה';d.append(s);const regions=c.images||c.regions;d.open=c.kind==='reading_passage'||c.kind==='quantitative_comparison_instructions'||c.kind==='shared_response_instructions'||(c.kind==='shared_instructions_or_chart'&&regions.some(r=>r.height>65));for(const r of regions)d.append(picture(r.asset,'מידע מקורי לשאלה'));return d;}
async function next(){if(!catalog)return;const token=++generation;progress.load();update();const selected=chooseQuestion(rows(),progress.state.mastered,current?.id,()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296);current=null;graded=false;$('answers').disabled=true;$('checkButton').disabled=true;$('nextButton').disabled=true;$('feedback').hidden=true;document.querySelectorAll('[name=answer]').forEach(r=>{r.checked=false;r.parentElement.classList.remove('correct','incorrect')});$('questionCard').hidden=!selected;$('emptyState').hidden=!!selected;if(!selected)return;$('questionCard').setAttribute('aria-busy','true');$('questionBody').textContent='טוענים שאלה…';try{if(!batches.has(selected.exam))batches.set(selected.exam,fetchJSON(`data/exams/${selected.exam}.json`).catch(e=>{batches.delete(selected.exam);throw e}));const batch=await batches.get(selected.exam);if(token!==generation)return;current=batch.questions[selected.id];$('subjectLabel').textContent=names[mode];$('questionTitle').textContent=`שאלה ${current.number}`;$('sourceTag').textContent=selected.exam.replace('he-','');$('questionBody').replaceChildren();const cs=current.contexts.map(id=>batch.contexts[id]).filter(Boolean);for(const c of cs.filter(c=>c.kind!=='complete_section_fallback'&&c.kind!=='section_instructions'))$('questionBody').append(context(c));for(const r of current.regions)$('questionBody').append(picture(r.asset,'השאלה והתשובות המקוריות'));const hint=document.createElement('p');hint.className='image-hint';hint.textContent='לחצו על התמונה להגדלה';$('questionBody').append(hint);for(const c of cs.filter(c=>c.kind==='complete_section_fallback'||c.kind==='section_instructions'))$('questionBody').append(context(c));$('answers').disabled=false;$('nextButton').disabled=false;$('nextButton').textContent='שאלה אחרת';}catch{if(token!==generation)return;$('questionBody').textContent='לא הצלחנו לטעון את השאלה. נסו שוב.';$('nextButton').disabled=false;$('nextButton').textContent='ניסיון נוסף';}finally{if(token===generation)$('questionCard').setAttribute('aria-busy','false');}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));next()});
document.querySelectorAll('[name=answer]').forEach(r=>r.onchange=()=>{$('checkButton').disabled=!current||graded});
$('nextButton').onclick=next;
$('checkButton').onclick=async()=>{const q=current,token=generation,label=Number(document.querySelector('[name=answer]:checked')?.value);if(!q||graded||!label)return;graded=true;$('answers').disabled=true;$('checkButton').disabled=true;try{const ok=await checkAnswer(q,label),answer=ok?label:await correctLabel(q);if(token!==generation)return;progress.record(q.id,ok);update();$('feedback').className=ok?'feedback correct':'feedback incorrect';$('feedback').textContent=ok?'נכון! השאלה הושלמה ולא תופיע שוב.':`התשובה הנכונה היא ${answer}. השאלה נשארת לתרגול.`;$('feedback').hidden=false;document.querySelector(`[name=answer][value="${answer}"]`).parentElement.classList.add('correct');if(!ok)document.querySelector(`[name=answer][value="${label}"]`).parentElement.classList.add('incorrect');$('nextButton').textContent='שאלה הבאה';}catch{graded=false;$('answers').disabled=false;$('checkButton').disabled=false;$('feedback').hidden=false;$('feedback').textContent='הבדיקה נכשלה. נסו שוב.';}};
$('closeZoom').onclick=()=>$('zoomDialog').close();$('zoomRange').oninput=()=>{$('zoomImage').style.width=$('zoomRange').value+'%'};
$('settingsButton').onclick=()=>{if(!progress)return;$('totalProgress').textContent=`${Object.keys(progress.state.mastered).length.toLocaleString('he')} מתוך ${catalog.questions.length.toLocaleString('he')} שאלות הושלמו`;$('settingsDialog').showModal()};$('closeSettings').onclick=()=>$('settingsDialog').close();
$('exportButton').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(progress.state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='psychometric-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)};
$('importInput').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('Too large');progress.import(JSON.parse(await f.text()));$('importFeedback').textContent='הגיבוי יובא בהצלחה.';await next();}catch{$('importFeedback').textContent='לא ניתן לקרוא את הגיבוי. בחרו קובץ התקדמות תקין.';}e.target.value=''};
$('resetButton').onclick=()=>{$('resetConfirm').hidden=false};$('cancelReset').onclick=()=>{$('resetConfirm').hidden=true};$('confirmReset').onclick=()=>{progress.reset();$('resetConfirm').hidden=true;$('settingsDialog').close();next()};
window.addEventListener('storage',e=>{if(e.key===key){progress.load();if(current&&Object.hasOwn(progress.state.mastered,current.id))next();else update()}});
async function init(){try{catalog=await fetchJSON('data/catalog.json');progress=new Progress(storage,key,new Set(catalog.questions.map(q=>q.id)));await next()}catch{$('questionBody').textContent='טעינת המאגר נכשלה. בדקו את החיבור ורעננו את הדף.'}}init();
